### ISSUE TITLE
StrimziKafkaWithRegistryMessagingIT is flaky in Native mode

### ISSUE THREAD

**Issue by fedinskiy** [quarkus-qe/quarkus-test-framework#1186]
When run in native mode, the test sometimes fails with the following errors:

```
2024-06-27T14:34:33.5305623Z 2024-06-27 14:34:33,509 ERROR [tc.qua.io/.41.0-k.7.0] (main) Log output from the failed container:
2024-06-27T14:34:33.5306374Z usage: kafka-storage format [-h] --config CONFIG --cluster-id CLUSTER_ID
2024-06-27T14:34:33.5306949Z                      [--add-scram ADD_SCRAM] [--ignore-formatted]
2024-06-27T14:34:33.5307420Z                      [--release-version RELEASE_VERSION]
2024-06-27T14:34:33.5307961Z kafka-storage: error: argument --cluster-id/-t: expected one argument
2024-06-27T14:34:33.5308852Z [2024-06-27 14:29:35,511] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
2024-06-27T14:34:33.5310217Z [2024-06-27 14:29:35,732] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2024-06-27T14:34:33.5311351Z [2024-06-27 14:29:35,796] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
2024-06-27T14:34:33.5311986Z java.lang.RuntimeException: No readable meta.properties files found.
2024-06-27T14:34:33.5312789Z 	at org.apache.kafka.metadata.properties.MetaPropertiesEnsemble.verify(MetaPropertiesEnsemble.java:493)
2024-06-27T14:34:33.5313663Z 	at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:152)
2024-06-27T14:34:33.5314302Z 	at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:60)
2024-06-27T14:34:33.5314782Z 	at kafka.Kafka$.buildServer(Kafka.scala:82)
2024-06-27T14:34:33.5315144Z 	at kafka.Kafka$.main(Kafka.scala:90)
2024-06-27T14:34:33.5315474Z 	at kafka.Kafka.main(Kafka.scala)
```

**Comment by fedinskiy** [comment]
Investigation result: this happens inside testcontainers code due to malformed cluster id (eg `-Mk3vxQVTc-iWEuxW2zREA`) which kafka considers to be a flag. I created the following issue, but maybe we just need to drop usage of this library/method altogether

**Comment by jcarranzan** [comment]
This also happens in JVM build, as I figured  out from the last daily builds failed, for instance: 
https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/9849583783/job/27193907778 .
And this has been occurring frequently in the latest builds.

**Comment by jedla97** [comment]
@fedinskiy can we close this? I see that https://github.com/quarkus-qe/quarkus-test-framework/pull/1207 was merged but this wasn't auto-closed.

**Comment by fedinskiy** [comment]
@jedla97 now, when we've updated to 0.107.0, we can close this.
